import { prisma } from "@/server/db";
import { saveMasterData, setMasterDataDeleted } from "@/server/master-data";

const formatMoney = (value: { toString(): string } | number) => `${Number(value).toLocaleString("vi-VN")} ₫`;
const Field = ({ name, label, type = "text", defaultValue, required = false }: { name: string; label: string; type?: string; defaultValue?: string | number; required?: boolean }) => <label className="block text-sm"><span className="mb-1 block text-ink/70">{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue} className="w-full rounded border border-line px-3 py-2" /></label>;
const Active = () => <label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked />Đang sử dụng</label>;

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [branches, models, films, services, categories, params] = await Promise.all([
    prisma.branch.findMany({ orderBy: { name: "asc" } }), prisma.cameraModel.findMany({ orderBy: { name: "asc" } }), prisma.filmType.findMany({ orderBy: { name: "asc" } }), prisma.printService.findMany({ orderBy: { name: "asc" } }), prisma.transactionCategory.findMany({ orderBy: { name: "asc" } }), searchParams,
  ]);
  return <div className="space-y-10 max-w-6xl"><header><h1 className="text-2xl font-semibold">Cài đặt dữ liệu nền</h1><p className="mt-1 text-sm text-ink/60">Quản lý các dữ liệu dùng chung cho đơn hàng và báo cáo.</p></header>{params.notice && <p className="rounded bg-green-50 p-3 text-sm text-green-800">{params.notice}</p>}{params.error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{params.error}</p>}
    <section className="grid gap-6 lg:grid-cols-2"><Form title="Cơ sở mới" entity="branch"><Field name="name" label="Tên cơ sở" required /><Field name="address" label="Địa chỉ" /><Field name="notes" label="Ghi chú" /></Form><List title="Cơ sở" items={branches} entity="branch" render={(x) => <><b>{x.name}</b><span>{x.address ?? "Chưa có địa chỉ"}</span></>} /></section>
    <section className="grid gap-6 lg:grid-cols-2"><Form title="Model máy mới" entity="cameraModel"><Field name="name" label="Tên model" required /><Field name="defaultBookingDeposit" label="Cọc giữ chỗ mặc định" type="number" defaultValue={40000} required /><Field name="defaultPrice1day" label="Giá thuê 1 ngày mặc định" type="number" /><Field name="defaultPriceCombo3" label="Giá combo 3 ngày mặc định" type="number" /><Field name="description" label="Mô tả" /><Active /></Form><List title="Model máy" items={models} entity="cameraModel" render={(x) => <><b>{x.name}</b><span>Cọc {formatMoney(x.defaultBookingDeposit)} · {x.active ? "Đang dùng" : "Ngưng dùng"}</span></>} /></section>
    <section className="grid gap-6 lg:grid-cols-2"><Form title="Loại phim mới" entity="filmType"><Field name="name" label="Tên loại phim" required /><Field name="defaultSalePrice" label="Giá bán mặc định" type="number" required /><Active /></Form><List title="Loại phim" items={films} entity="filmType" render={(x) => <><b>{x.name}</b><span>{formatMoney(x.defaultSalePrice)} · {x.active ? "Đang dùng" : "Ngưng dùng"}</span></>} /></section>
    <section className="grid gap-6 lg:grid-cols-2"><Form title="Dịch vụ in mới" entity="printService"><Field name="name" label="Tên dịch vụ" required /><Field name="unitPrice" label="Đơn giá" type="number" required /><Active /></Form><List title="Dịch vụ in" items={services} entity="printService" render={(x) => <><b>{x.name}</b><span>{formatMoney(x.unitPrice)} · {x.active ? "Đang dùng" : "Ngưng dùng"}</span></>} /></section>
    <section className="grid gap-6 lg:grid-cols-2"><Form title="Danh mục tài chính mới" entity="transactionCategory"><Field name="name" label="Tên danh mục" required /><label className="block text-sm"><span className="mb-1 block text-ink/70">Loại</span><select name="transactionType" className="w-full rounded border border-line px-3 py-2"><option value="EXPENSE">Chi phí</option><option value="INCOME">Thu nhập khác</option></select></label><Active /></Form><List title="Danh mục tài chính" items={categories} entity="transactionCategory" render={(x) => <><b>{x.name}</b><span>{x.transactionType === "EXPENSE" ? "Chi phí" : "Thu nhập"} · {x.active ? "Đang dùng" : "Ngưng dùng"}</span></>} /></section>
  </div>;
}
function Form({ title, entity, children }: { title: string; entity: string; children: React.ReactNode }) { return <form action={saveMasterData} className="rounded-lg border border-line bg-white p-5 shadow-sm"><h2 className="mb-4 font-medium">{title}</h2><input type="hidden" name="entity" value={entity} /><div className="grid gap-3 sm:grid-cols-2">{children}</div><button className="mt-5 rounded bg-accent px-4 py-2 text-sm font-medium text-paper">Lưu</button></form>; }
function List<T extends { id: string; deletedAt?: Date | null }>({ title, items, entity, render }: { title: string; items: T[]; entity: string; render: (item: T) => React.ReactNode }) { return <div className="rounded-lg border border-line bg-white p-5"><h2 className="mb-4 font-medium">{title}</h2><div className="divide-y divide-line">{items.filter((x) => !x.deletedAt).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 py-3 text-sm"><div className="grid">{render(item)}</div><form action={setMasterDataDeleted}><input type="hidden" name="entity" value={entity}/><input type="hidden" name="id" value={item.id}/><button className="text-red-700">Xóa</button></form></div>)}{items.filter((x) => !x.deletedAt).length === 0 && <p className="py-3 text-sm text-ink/50">Chưa có dữ liệu.</p>}</div></div>; }
