import Link from "next/link";
import { prisma } from "@/server/db";
import { saveMasterData, setMasterDataDeleted } from "@/server/master-data";
const money = (v: { toString(): string }) => `${Number(v).toLocaleString("vi-VN")} ₫`;
export default async function CamerasPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
 const [models, branches, cameras, params] = await Promise.all([prisma.cameraModel.findMany({where:{deletedAt:null,active:true},orderBy:{name:"asc"}}), prisma.branch.findMany({where:{deletedAt:null},orderBy:{name:"asc"}}), prisma.cameraInstance.findMany({include:{cameraModel:true,branch:true},orderBy:{assetCode:"asc"}}), searchParams]);
 return <div className="max-w-6xl space-y-6"><header><h1 className="text-2xl font-semibold">Máy ảnh</h1><p className="mt-1 text-sm text-ink/60">Tạo tài sản vật lý; giá thuê được lưu riêng cho từng máy.</p></header>{params.notice&&<p className="rounded bg-green-50 p-3 text-sm text-green-800">{params.notice}</p>}{params.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{params.error}</p>}
 <form action={saveMasterData} className="grid gap-3 rounded-lg border border-line bg-white p-5 shadow-sm md:grid-cols-3"><input type="hidden" name="entity" value="cameraInstance"/><label className="text-sm">Model<select required name="cameraModelId" className="mt-1 w-full rounded border border-line p-2"><option value="">Chọn model</option>{models.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">Cơ sở<select required name="branchId" className="mt-1 w-full rounded border border-line p-2"><option value="">Chọn cơ sở</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">Mã máy<input required name="assetCode" className="mt-1 w-full rounded border border-line p-2"/></label><label className="text-sm">Giá thuê 1 ngày<input required type="number" min="0" name="price1day" className="mt-1 w-full rounded border border-line p-2"/></label><label className="text-sm">Giá combo 3 ngày<input required type="number" min="0" name="priceCombo3" className="mt-1 w-full rounded border border-line p-2"/></label><label className="text-sm">Phim còn trong máy<input required type="number" min="0" defaultValue="0" name="filmRemaining" className="mt-1 w-full rounded border border-line p-2"/></label><label className="text-sm">Trạng thái<select name="status" className="mt-1 w-full rounded border border-line p-2"><option value="IN_SERVICE">Đang phục vụ</option><option value="MAINTENANCE">Bảo trì</option><option value="RETIRED">Ngừng sử dụng</option></select></label><label className="text-sm">Giá mua<input type="number" min="0" name="purchaseCost" className="mt-1 w-full rounded border border-line p-2"/></label><label className="text-sm">Ngày mua<input type="date" name="purchaseDate" className="mt-1 w-full rounded border border-line p-2"/></label><label className="text-sm md:col-span-2">Ghi chú<input name="notes" className="mt-1 w-full rounded border border-line p-2"/></label><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" name="active" defaultChecked/>Đang sử dụng</label><button className="rounded bg-accent px-4 py-2 text-sm font-medium text-paper md:col-span-3">Thêm máy</button></form>
 <div className="overflow-x-auto rounded-lg border border-line bg-white"><table className="w-full text-left text-sm"><thead className="border-b border-line bg-ink/5 text-ink/70"><tr><th className="p-3">Mã máy</th><th className="p-3">Model / Cơ sở</th><th className="p-3">Giá thuê</th><th className="p-3">Trạng thái</th><th className="p-3"/></tr></thead><tbody>{cameras.filter(x=>!x.deletedAt).map(x=><tr key={x.id} className="border-b border-line"><td className="p-3 font-medium">{x.assetCode}</td><td className="p-3">{x.cameraModel.name}<br/><span className="text-ink/55">{x.branch.name}</span></td><td className="p-3">{money(x.price1day)} / ngày<br/>{money(x.priceCombo3)} / 3 ngày</td><td className="p-3">{x.status}</td><td className="p-3"><form action={setMasterDataDeleted}><input type="hidden" name="entity" value="cameraInstance"/><input type="hidden" name="id" value={x.id}/><button className="text-red-700">Xóa</button></form></td></tr>)}{cameras.filter(x=>!x.deletedAt).length===0&&<tr><td colSpan={5} className="p-5 text-ink/50">Chưa có máy. Hãy <Link href="/settings" className="text-accent underline">tạo model và cơ sở</Link> trước.</td></tr>}</tbody></table></div></div>;
}
